### ISSUE TITLE
Make the background of forms responsive 

### ISSUE THREAD

**Issue by isauwwebdev** [isauwwebdev/isauwwebsite#37]
As of now, the background of events sign up forms is divided into two halves:
1. The actual background image at the top half
2. White space at the bottom half
The process of having to crop the BG image is repetitive and tedious - especially for the design team. Also, any changes in the dimensions of the BG might result in a lack of responsivity (BG moves when opening the drop down options of the form). 
### Expected results
We want to implement the BG (white part) using code, making it responsive.

### Implementation suggestions:
Use breakpoints, responsive height, vh, etc to achieve a consistent BG to White ratio, according to the example image attached below. Make sure the ratio remains in all medias.  

Might want to check on eventsSignUpForm.tsx line 296 

Feel free to clarify more questions if you have. 

Attached is an example of the BG that we are using now.  
![stampQuestFormBG](https://github.com/user-attachments/assets/d0de428a-4e67-4836-896a-3151d77d332a)

**Comment by enricopratama** [comment]
Closed with pr #52
